{
 "title": "ONEC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "exported_instance",
    "label": "Application",
    "query": {
     "query": "label_values(exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "APDEX by infobase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"1\"}) by (exported_instance)\r\n+\r\n  (sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"+Inf\"}) by (exported_instance) \r\n    - sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"1\"}) by (exported_instance)) / 2)\r\n/\r\nsum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"+Inf\"}) by (exported_instance)"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by(exported_instance) (onec_active_users{exported_instance=~\"$exported_instance\"})"
    }
   ]
  },
  {
   "title": "APDEX by key operations",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"+Inf\"}) by (exported_instance,keyoperation)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"1\"}) by (exported_instance, keyoperation)\r\n+\r\n  (sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"+Inf\"}) by (exported_instance, keyoperation) \r\n    - sum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"1\"}) by (exported_instance,keyoperation)) \r\n  /2)\r\n/\r\nsum(onec_key_operation_apdex_score_bucket{exported_instance=~\"$exported_instance\",le=\"+Inf\"}) by (exported_instance, keyoperation)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}